<?php

function teacher_dashboard_mods_views_pre_render(&$view) {

  if ($view->name=='teacher_calendar_assignments') {

    drupal_set_message('<pre>' . print_r($view->result, TRUE) . '</pre>');

	foreach($view->result as $r => $result) {
      if ($result->node_type == 'otw_assignment') { 
      	drupal_set_message('It iss!!');//$result->_field_data->nid->entity->title = '<h1>' . $result->_field_data->nid->entity->title . 'Blahhh</h1>';
      	drupal_set_message(print_r($result->_field_data->nid->entity->title,TRUE));
      }
	}

  }

}

?>