Lionworxs.Class = DS.Model.extend
  author: DS.belongsTo('user')
  name: DS.attr('string')
  description: DS.attr('string')
  school: DS.belongsTo('school')
  grading_system: DS.hasMany('gradingSystem')
  administrators: DS.hasMany('user')
  teachers: DS.hasMany('user')
  students: DS.hasMany('user')
  assignments: DS.hasMany('assignment')
  active: DS.hasMany('boolean')
