Lionworxs.User = DS.Model.extend
  name: DS.attr('string')
  email: DS.attr('string')
  password: DS.attr('string')
  date_registered: DS.attr('date')
  last_login: DS.attr('date')
  schools: DS.hasMany('school')
  classes_taught: DS.hasMany('class')
  classes_enrolled: DS.hasMany('class')
  children: DS.hasMany('user')
  parents: DS.hasMany('user')
  user_settings: DS.hasMany('userSettings')
  avatar: DS.hasMany('string')
  phone: DS.hasMany('number')
  age: DS.hasMany('number')
