# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8a89c77ccb3940764d80d86147186b0bd1859f25ac6518dabd4558df681495293695855d3ab141ca4aa4f6e6a0b98ce2ff615a874e2a0d47ebca1bc246f835c

test:
  secret_key_base: 866c8fc5cd416436f7d807ba99b04850e95585d854c11db71eb005eb2532a8b41a771062c01f2ae634acb73cf698b5472eeec54da468c35b064a563b26a35b42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
